# Generated by Django 5.1.1 on 2024-11-06 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('consumptionID', models.AutoField(primary_key=True, serialize=False)),
                ('readingDateFrom', models.DateField()),
                ('readingDateTo', models.DateField()),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappcrud.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('billID', models.AutoField(primary_key=True, serialize=False)),
                ('billDate', models.DateField()),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dueDate', models.DateField()),
                ('tariffID', models.IntegerField()),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappcrud.customer')),
            ],
        ),
    ]
